### ISSUE TITLE
Check branch other than master

### ISSUE THREAD

**Issue by marians** [gojp/goreportcard#168] opened 2016-11-19 19:53 UTC
I don't see an option to check an arbitrary branch of a git repository. However that would be quite helpful as a quality insurance step _before_ merging a PR into master.

**Comment by onuryilmaz** [comment] 2016-12-14 08:38
I think this feature could help a lot:
- Listen for Github hooks on PR events
- Run checks and save result on a temporary URL (since it would be clicked from merge checks)
- Write response to PR check (for merge checks)

**Comment by shawnps** [comment] 2017-01-06 22:37
Going to close this as a duplicate of https://github.com/gojp/goreportcard/issues/96 but I'll carry your comments over. Thanks

**Closed by shawnps** 2017-01-06 22:37 UTC
