### ISSUE TITLE
Oops! There was an error processing your request: {}

### ISSUE THREAD

**Issue by bwmarrin** [gojp/goreportcard#60] opened 2016-02-01 14:26 UTC
Not sure if this is the best place to report this, but I don't know of anywhere else :)

When trying to update the score for my repo bwmarrin/discordgo I am getting the below error

```
Oops! There was an error processing your request: {}
```

But this seems to work fine for other repo's I have so I'm unsure if somehow there's something I've done in my discordgo repo that's causing a problem :(    I would like to get it updated as I've fixed a bunch of things and like anybody else I want a good score :)

**Comment by shawnps** [comment] 2016-02-01 14:39
Hi @bwmarrin 

This has happened in the past and I think in this case it's related to the default branch being "develop" rather than "master".

I'll try to reproduce locally and fix it in the long term, but in the meantime I've reset the repo and I think it should work now. Let me know if it happens again or the output isn't what you expected

**Comment by shawnps** [comment] 2016-02-01 14:40
Spoke too soon, looks like clicking Update now breaks. I'm almost certain it has something to do with the branches because this is the error I see:

`2016/02/01 09:39:43 ERROR:  Could not clone repo: could not reset origin/master: exit status 128`

I'll try to investigate soon

**Comment by bwmarrin** [comment] 2016-02-01 15:00
Thanks.  Just FYI I've had the branches set like this for awhile and it's been working (I thought).

Maybe this is just another reason to just use master :)

**Comment by shawnps** [comment] 2016-02-07 05:39
I think this is fixed now that we call `go get` in the backend rather than call out to `git` directly. We can reopen if it happens again.

**Closed by shawnps** 2016-02-07 05:39 UTC

**Comment by bwmarrin** [comment] 2016-02-07 16:51
Ah, thanks.  So that means this will always test vs whatever `go get` gets, which is master, right?
