### ISSUE TITLE
False go vet error

### ISSUE THREAD

**Issue by ahmetalpbalkan** [gojp/goreportcard#170] opened 2017-01-05 00:44 UTC
I have a small project https://github.com/ahmetalpbalkan/dlog

It gives the following vet error on goreportcard: https://goreportcard.com/report/github.com/ahmetalpbalkan/dlog

     Line 14: error: ExampleNewReader refers to unknown identifier: NewReader (vet)

However I can't reproduce this error locally with `go vet ./...` or on Travis CI, with go1.7.

Any ideas?

**Comment by shawnps** [comment] 2017-01-06 23:17
@ahmetalpbalkan I think this is a duplicate of https://github.com/gojp/goreportcard/issues/113

Still not sure what's going on but I'll close this as a duplicate and investigate soon hopefully.

**Closed by shawnps** 2017-01-06 23:17 UTC
