### ISSUE TITLE
error: "Could not go get the repository"

### ISSUE THREAD

**Issue by mdlayher** [gojp/goreportcard#90] opened 2016-02-21 23:55 UTC
Hello!

I've tried a few times to set up Go Report Card for my repo here: https://goreportcard.com/report/github.com/mdlayher/unifi_exporter.

However, every time I try, I receive the error listed in the title.  I suspect this may be because of a mismatch between the package name `unifiexporter` and the repository `unifi_exporter`, but would be curious if you all had any thoughts on the matter.

Thanks for this great service!

**Comment by hermanschaaf** [comment] 2016-02-22 05:31
Thanks for reporting!

I looked into this for a couple of minutes, and I'm not sure what's going on yet. In the logs I can see:

```
2016/02/22 00:11:03 Go getting "github.com/mdlayher/unifi_exporter"...
2016/02/22 00:11:08 Go get error log: # cd /repos/src/github.com/mdlayher/unifi; git pull --ff-only
fatal: Not possible to fast-forward, aborting.
package github.com/mdlayher/unifi: exit status 128

2016/02/22 00:11:08 Go getting "github.com/mdlayher/unifi_exporter"...
2016/02/22 00:11:14 Go get error log: # cd /repos/src/github.com/mdlayher/unifi; git pull --ff-only
fatal: Not possible to fast-forward, aborting.
package github.com/mdlayher/unifi: exit status 128

2016/02/22 00:11:14 ERROR: from newChecksResp: could not clone repo: could not run go get: exit status 1
```

The relevant code in our codebase is here: https://github.com/gojp/goreportcard/blob/master/handlers/checks.go#L75-L120

What's weird is that it logs the correct repo name, `github.com/mdlayher/unifi_exporter`, does nothing to change it, calls `go get` with that same name, and then somehow the go get command loses the part of the name past the underscore. Running `go get -u -d github.com/mdlayher/unifi_exporter` in the shell directly does not have this problem.

The second time it logs the same message is because if the first attempt fails, we delete the corresponding cached local directory, and try again.

Anyone want to look into this?

**Comment by h2non** [comment] 2016-02-26 12:49
Same issue with: `github.com/resilient-http/resilient.go`

**Comment by henvic** [comment] 2016-03-09 21:46
+1

Same problem here when trying to get report for github.com/launchpad-project/api.go.

**Comment by shafreeck** [comment] 2016-04-15 03:07
Same problem with : github.com/shafreeck/fperf

**Comment by alkchr** [comment] 2016-04-15 07:47
Possibly, a way to reproduce the issue:

1. Create a new repo with some Go project, ask `goreportcard` to check it.
2. Remove the repo and create again with new git history (maybe, history rewrite will do the trick, too), ask `goreportcard` to check it again to see the error below.

```
2016/04/15 11:51:32 Go getting "github.com/username/test"...
2016/04/15 11:51:34 Go get error log: # cd /home/johndoe/Develop/go/src/github.com/gojp/goreportcard/repos/src/github.com/username/test; git pull --ff-only
warning: no common commits
From https://github.com/username/test
 + 9784a07...f728e25 master     -> origin/master  (forced update)
fatal: Not possible to fast-forward, aborting.
package github.com/username/test: exit status 128
```

Repos ending with `.go` are not related to the issue. And `github.com/shafreeck/fperf` is not go gettable (GNU/Linux 4.4.6 x86_64, Go 1.5.3, Git 2.5.5).

**Comment by hermanschaaf** [comment] 2016-04-15 07:56
@alkchr Actually, goreportcard already does exactly as you suggested, [see the code here](https://github.com/gojp/goreportcard/blob/f0eb50fcb2ab23574b7d4ee6e634485d495aa9af/handlers/checks.go#L112-L122).

The remaining issue is something we did not foresee at the time, which is that `go get` not only fails if the repo itself has a rewritten history, but also if any one of the repo's *dependencies* has a rewritten git history.

So to fix this, I would suggest something like the following:
 1. try go get, if it fails,
 2. read the error message, and extract the name of the repo that failed. Delete that repo, and try again. If it fails with a different message, repeat this step.
 3. If the `go get` command fails twice with the same error, return failure.

**Comment by mweagle** [comment] 2016-04-26 17:46
Same problem with: [github.com/mweagle/Sparta](github.com/mweagle/Sparta)

Even as a workaround, I'd be willing to manually delete the cached repo(s) from Go via a UI option. Appreciate the great tool - thanks.

**Comment by AkihiroSuda** [comment] 2016-04-28 08:15
Same problem with: https://github.com/osrg/namazu
https://goreportcard.com/report/github.com/osrg/namazu

Note that we recently renamed `osrg/earthquake` to `osrg/namazu`.
goreportcard had been working before renaming that.

**Comment by shawnps** [comment] 2016-04-28 10:44
@AkihiroSuda please try again, seems to be working for me.

**Comment by shawnps** [comment] 2016-04-28 10:45
@mweagle please try again, I believe the issue was that we ran out of disk on the server and couldn't `go get` anything. I'll see about putting some sort of monitor on it or cron to clean up the repos we store on disk.

**Comment by shawnps** [comment] 2016-04-28 10:46
@mdlayher yours appears to be working as well, I was able to update just a second ago

**Comment by shawnps** [comment] 2016-04-28 10:49
@h2non @henvic I suspect the issue with your repos is that `go get` does in fact exit status 1 when trying to get them:

```
➜  ~   go get -u github.com/launchpad-project/api.go
stat github.com/launchpad-project/api.go: no such file or directory
➜  ~  go get -u github.com/resilient-http/resilient.go
stat github.com/resilient-http/resilient.go: no such file or directory
➜  ~  echo $?
1
```

The only thing I can think of is that because your repo names have `.go` in them, `go get` is trying to do something special. I don't know why. I'm not sure if ignoring exit status 1 is the right answer, will have to think about it.

**Comment by shawnps** [comment] 2016-04-28 10:51
@shafreeck yours appears to be working as well...I'm going to assume the issue was disk space and at some point a couple weeks ago I probably cleared up the space on the server but did not think to correlate that problem to this ticket.

**Comment by AkihiroSuda** [comment] 2016-04-28 11:10
Now it works, thanks!

**Comment by mweagle** [comment] 2016-04-28 14:18
@shawnps - Works great, thanks for looking into it.

**Comment by hermanschaaf** [comment] 2016-04-28 14:22
After deploying #119, this should be fixed now, so I'm closing this ticket. If you still get a "could not go get repo" error, it's probably best to open a new ticket, since the reasons are not always the same. Hopefully this fixes it for the majority of cases though!

**Closed by hermanschaaf** 2016-04-28 14:22 UTC
Labels: help wanted

**Comment by AlexanderMatveev** [comment] 2022-05-12 01:02
@hermanschaaf same here https://goreportcard.com/report/github.com/AlexanderMatveev/gentls
