### ISSUE TITLE
Repository error when processing request

### ISSUE THREAD

**Issue by peter-edge** [gojp/goreportcard#58] opened 2016-01-16 20:19 UTC
github.com/peter-edge/flights-go

I cloned goreportcard locally and ran it, it works fine and shows 0 issues across 3 files.

Can we debug? Maybe also add a way to see what the error is when running?

**Comment by shurcooL** [comment] 2016-01-17 02:07
It'd be nice to be able to see the error details to debug this.

I noticed your Go package has a different canonical import path:

```
package flights // import "go.pedge.io/flights"
```

I wonder if that's something goreportcard doesn't support?

**Comment by peter-edge** [comment] 2016-01-17 02:09
Of note, it works with the rest of my (also custom import path) repos:
go.pedge.io

**Comment by shawnps** [comment] 2016-01-17 02:50
@peter-edge I just checked the server log and saw this:

```
2016/01/16 21:11:52 ERROR:  Could not clone repo: could not reset origin/master: exi
t status 128
```

Not sure what happened to be honest. I removed the repo that was stored on the server and tested it again on Go Report Card and it worked. Will leave this issue open and try to reproduce the error.

**Comment by peter-edge** [comment] 2016-01-17 02:57
This is a weird situation but I think I know: I had a repo briefly that I
deleted before that had the same name. So this is trying to pull a
different repo. Cheap hack is to ignore cache and delete repo on the server
if exitStatus == 128.

**Comment by shawnps** [comment] 2016-01-17 03:02
@peter-edge ah, yeah that is probably it. I think your suggestion about deleting the repo on exitStatus == 128 makes sense.

**Comment by shurcooL** [comment] 2016-01-17 03:34
Maybe it was failing to fast-forward because it had a different repo checked out previously.

Deleting the old repo, or fetching and doing a hard reset to origin/master should fix that problem.

**Comment by shawnps** [comment] 2016-02-07 05:49
Hoping this is fixed now with the new way of pulling repos down. Closing but feel free to reopen if anyone notices any weirdness.

**Closed by shawnps** 2016-02-07 05:49 UTC
